name: First Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Step 1 complete!"

      - name: Step 2
        run: echo "Step 2 complete!"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Use Cowsays action
        uses: mscoutermarsh/cowsays-action@v1
        with:
          text: "Ready for prod–ship it!"
          color: magenta